version: 2.1

orbs:
  ta-python: travelaudience/python@1.1.2

workflows:
  main:
    jobs:
      - ta-python/flake8
      - ta-python/test:
          ci_requirements: ''
          install_pytest: true
          with_coverage: false